{
    "formatVersion": "1.1",
    "component": {
        "group": "eu.hansolo.fx",
        "module": "charts",
        "version": "21.0.19",
        "attributes": {
            "org.gradle.status": "release"
        }
    },
    "createdBy": {
        "gradle": {
            "version": "8.9"
        }
    },
    "variants": [
        {
            "name": "apiElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.jvm.version": 21,
                "org.gradle.libraryelements": "jar",
                "org.gradle.usage": "java-api"
            },
            "dependencies": [
                {
                    "group": "eu.hansolo.fx",
                    "module": "countries",
                    "version": {
                        "requires": "21.0.19"
                    }
                }
            ],
            "files": [
                {
                    "name": "charts-21.0.19.jar",
                    "url": "charts-21.0.19.jar",
                    "size": 1957844,
                    "sha512": "a979a4fcc25dd5a9fbf86c6f85203a7f83914d0d716541305b5db7c50b3b7489d2c819167cbd1f1c9f12c6e74f30b381f11e75759872d5693bb5111b9f39509b",
                    "sha256": "4c5ddd92e9a7482efa8e21210b194ba3e5527e4a65a6b9afb0fd5eed10b42a58",
                    "sha1": "f25d5c0900266a3aae3af0b7df29e5b885012ae8",
                    "md5": "7425af9f143ea6511237c150686833bc"
                }
            ]
        },
        {
            "name": "runtimeElements",
            "attributes": {
                "org.gradle.category": "library",
                "org.gradle.dependency.bundling": "external",
                "org.gradle.jvm.version": 21,
                "org.gradle.libraryelements": "jar",
                "org.gradle.usage": "java-runtime"
            },
            "dependencies": [
                {
                    "group": "org.openjfx",
                    "module": "javafx-base",
                    "version": {
                        "requires": "21.0.4"
                    }
                },
                {
                    "group": "org.openjfx",
                    "module": "javafx-graphics",
                    "version": {
                        "requires": "21.0.4"
                    }
                },
                {
                    "group": "org.openjfx",
                    "module": "javafx-controls",
                    "version": {
                        "requires": "21.0.4"
                    }
                },
                {
                    "group": "org.openjfx",
                    "module": "javafx-swing",
                    "version": {
                        "requires": "21.0.4"
                    }
                },
                {
                    "group": "ch.qos.logback",
                    "module": "logback-classic",
                    "version": {
                        "requires": "1.3.9"
                    }
                },
                {
                    "group": "eu.hansolo.fx",
                    "module": "countries",
                    "version": {
                        "requires": "21.0.19"
                    }
                }
            ],
            "files": [
                {
                    "name": "charts-21.0.19.jar",
                    "url": "charts-21.0.19.jar",
                    "size": 1957844,
                    "sha512": "a979a4fcc25dd5a9fbf86c6f85203a7f83914d0d716541305b5db7c50b3b7489d2c819167cbd1f1c9f12c6e74f30b381f11e75759872d5693bb5111b9f39509b",
                    "sha256": "4c5ddd92e9a7482efa8e21210b194ba3e5527e4a65a6b9afb0fd5eed10b42a58",
                    "sha1": "f25d5c0900266a3aae3af0b7df29e5b885012ae8",
                    "md5": "7425af9f143ea6511237c150686833bc"
                }
            ]
        }
    ]
}